# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Aug 31 15:55:31 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1224, 1057)
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.freqBar = QtGui.QSlider(self.centralwidget)
        self.freqBar.setMinimum(0)
        self.freqBar.setMaximum(0)
        self.freqBar.setSliderPosition(0)
        self.freqBar.setTracking(False)
        self.freqBar.setOrientation(QtCore.Qt.Horizontal)
        self.freqBar.setInvertedAppearance(False)
        self.freqBar.setInvertedControls(False)
        self.freqBar.setTickPosition(QtGui.QSlider.TicksBelow)
        self.freqBar.setObjectName(_fromUtf8("freqBar"))
        self.horizontalLayout.addWidget(self.freqBar)
        self.freqLabel = QtGui.QLabel(self.centralwidget)
        self.freqLabel.setObjectName(_fromUtf8("freqLabel"))
        self.horizontalLayout.addWidget(self.freqLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSignal = QtGui.QMenu(self.menubar)
        self.menuSignal.setObjectName(_fromUtf8("menuSignal"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.propertiesList = QtGui.QTreeWidget(self.dockWidgetContents)
        self.propertiesList.setAlternatingRowColors(True)
        self.propertiesList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.propertiesList.setUniformRowHeights(True)
        self.propertiesList.setAnimated(True)
        self.propertiesList.setHeaderHidden(False)
        self.propertiesList.setColumnCount(2)
        self.propertiesList.setObjectName(_fromUtf8("propertiesList"))
        self.propertiesList.headerItem().setText(1, _fromUtf8("Value"))
        self.propertiesList.header().setCascadingSectionResizes(True)
        self.propertiesList.header().setDefaultSectionSize(180)
        self.propertiesList.header().setHighlightSections(True)
        self.propertiesList.header().setMinimumSectionSize(50)
        self.propertiesList.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.propertiesList)
        self.avgList = QtGui.QTreeWidget(self.dockWidgetContents)
        self.avgList.setAlternatingRowColors(True)
        self.avgList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.avgList.setUniformRowHeights(True)
        self.avgList.setAnimated(True)
        self.avgList.setHeaderHidden(False)
        self.avgList.setColumnCount(2)
        self.avgList.setObjectName(_fromUtf8("avgList"))
        self.avgList.headerItem().setText(1, _fromUtf8("Value"))
        self.avgList.header().setCascadingSectionResizes(True)
        self.avgList.header().setDefaultSectionSize(180)
        self.avgList.header().setHighlightSections(True)
        self.avgList.header().setMinimumSectionSize(50)
        self.avgList.header().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.avgList)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fsGo = QtGui.QPushButton(self.dockWidgetContents_2)
        self.fsGo.setObjectName(_fromUtf8("fsGo"))
        self.verticalLayout_2.addWidget(self.fsGo)
        self.dataBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.dataBox.setEnabled(True)
        self.dataBox.setObjectName(_fromUtf8("dataBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dataBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.dataBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.modeBox = QtGui.QComboBox(self.dataBox)
        self.modeBox.setEditable(False)
        self.modeBox.setObjectName(_fromUtf8("modeBox"))
        self.gridLayout_4.addWidget(self.modeBox, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.dataBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.windowBox = QtGui.QComboBox(self.dataBox)
        self.windowBox.setObjectName(_fromUtf8("windowBox"))
        self.gridLayout_4.addWidget(self.windowBox, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dataBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.peaksBox = QtGui.QSpinBox(self.dataBox)
        self.peaksBox.setMinimum(0)
        self.peaksBox.setMaximum(20)
        self.peaksBox.setProperty(_fromUtf8("value"), 5)
        self.peaksBox.setObjectName(_fromUtf8("peaksBox"))
        self.gridLayout_4.addWidget(self.peaksBox, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.dataBox)
        self.wgBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.wgBox.setObjectName(_fromUtf8("wgBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wgBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_13 = QtGui.QLabel(self.wgBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.wgFSR = QtGui.QDoubleSpinBox(self.wgBox)
        self.wgFSR.setObjectName(_fromUtf8("wgFSR"))
        self.gridLayout_2.addWidget(self.wgFSR, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.wgBox)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.wgBits = QtGui.QSpinBox(self.wgBox)
        self.wgBits.setPrefix(_fromUtf8(""))
        self.wgBits.setMinimum(1)
        self.wgBits.setMaximum(64)
        self.wgBits.setObjectName(_fromUtf8("wgBits"))
        self.gridLayout_2.addWidget(self.wgBits, 1, 1, 1, 1)
        self.wgFs = QtGui.QDoubleSpinBox(self.wgBox)
        self.wgFs.setPrefix(_fromUtf8(""))
        self.wgFs.setMaximum(200000000.0)
        self.wgFs.setObjectName(_fromUtf8("wgFs"))
        self.gridLayout_2.addWidget(self.wgFs, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.wgBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.wgBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.wgSamples = QtGui.QSpinBox(self.wgBox)
        self.wgSamples.setMinimum(1)
        self.wgSamples.setMaximum(65536)
        self.wgSamples.setObjectName(_fromUtf8("wgSamples"))
        self.gridLayout_2.addWidget(self.wgSamples, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.wgBox)
        self.acqBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.acqBox.setObjectName(_fromUtf8("acqBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.acqBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_17 = QtGui.QLabel(self.acqBox)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.adcFs = QtGui.QComboBox(self.acqBox)
        self.adcFs.setObjectName(_fromUtf8("adcFs"))
        self.gridLayout_3.addWidget(self.adcFs, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.acqBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.adcSamples = QtGui.QSpinBox(self.acqBox)
        self.adcSamples.setMinimum(1)
        self.adcSamples.setMaximum(65536)
        self.adcSamples.setObjectName(_fromUtf8("adcSamples"))
        self.gridLayout_3.addWidget(self.adcSamples, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.acqBox)
        self.fsBox = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.fsBox.setObjectName(_fromUtf8("fsBox"))
        self.gridLayout = QtGui.QGridLayout(self.fsBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.fsBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.fsStart = QtGui.QDoubleSpinBox(self.fsBox)
        self.fsStart.setPrefix(_fromUtf8(""))
        self.fsStart.setMaximum(200000000.0)
        self.fsStart.setObjectName(_fromUtf8("fsStart"))
        self.gridLayout.addWidget(self.fsStart, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.fsBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.fsEnd = QtGui.QDoubleSpinBox(self.fsBox)
        self.fsEnd.setPrefix(_fromUtf8(""))
        self.fsEnd.setMaximum(200000000.0)
        self.fsEnd.setObjectName(_fromUtf8("fsEnd"))
        self.gridLayout.addWidget(self.fsEnd, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.fsBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.fsSteps = QtGui.QSpinBox(self.fsBox)
        self.fsSteps.setMinimum(1)
        self.fsSteps.setMaximum(1024)
        self.fsSteps.setProperty(_fromUtf8("value"), 1)
        self.fsSteps.setObjectName(_fromUtf8("fsSteps"))
        self.gridLayout.addWidget(self.fsSteps, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.fsBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setIconVisibleInMenu(True)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew_Analysis = QtGui.QAction(MainWindow)
        self.actionNew_Analysis.setObjectName(_fromUtf8("actionNew_Analysis"))
        self.actionFull_Chain_rapid_test = QtGui.QAction(MainWindow)
        self.actionFull_Chain_rapid_test.setObjectName(_fromUtf8("actionFull_Chain_rapid_test"))
        self.actionDump = QtGui.QAction(MainWindow)
        self.actionDump.setObjectName(_fromUtf8("actionDump"))
        self.menuSignal.addAction(self.actionNew_Analysis)
        self.menuSignal.addSeparator()
        self.menuSignal.addAction(self.actionQuit)
        self.menubar.addAction(self.menuSignal.menuAction())
        self.toolBar.addAction(self.actionNew_Analysis)
        self.toolBar.addAction(self.actionFull_Chain_rapid_test)
        self.toolBar.addAction(self.actionDump)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionQuit)
        self.label_3.setBuddy(self.modeBox)
        self.label.setBuddy(self.windowBox)
        self.label_2.setBuddy(self.peaksBox)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ADC Characterization Toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.freqLabel.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSignal.setTitle(QtGui.QApplication.translate("MainWindow", "Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.propertiesList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.avgList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Property", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.fsGo.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBox.setTitle(QtGui.QApplication.translate("MainWindow", "Data analysis control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "&Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "&Window Function", None, QtGui.QApplication.UnicodeUTF8))
        self.windowBox.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose a signal window", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Ha&rmonics:", None, QtGui.QApplication.UnicodeUTF8))
        self.peaksBox.setStatusTip(QtGui.QApplication.translate("MainWindow", "How many harmonic peaks you want", None, QtGui.QApplication.UnicodeUTF8))
        self.peaksBox.setSuffix(QtGui.QApplication.translate("MainWindow", " peak(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.wgBox.setTitle(QtGui.QApplication.translate("MainWindow", "Wave synthesis control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "FSR", None, QtGui.QApplication.UnicodeUTF8))
        self.wgFSR.setSuffix(QtGui.QApplication.translate("MainWindow", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Number of bits", None, QtGui.QApplication.UnicodeUTF8))
        self.wgBits.setSuffix(QtGui.QApplication.translate("MainWindow", " bits", None, QtGui.QApplication.UnicodeUTF8))
        self.wgFs.setSuffix(QtGui.QApplication.translate("MainWindow", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Sampling rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.acqBox.setTitle(QtGui.QApplication.translate("MainWindow", "Acquisition control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Sampling rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.fsBox.setTitle(QtGui.QApplication.translate("MainWindow", "Frequency controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.fsStart.setSuffix(QtGui.QApplication.translate("MainWindow", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.fsEnd.setSuffix(QtGui.QApplication.translate("MainWindow", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open..", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Analysis.setText(QtGui.QApplication.translate("MainWindow", "New Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Chain_rapid_test.setText(QtGui.QApplication.translate("MainWindow", "Full Chain rapid test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDump.setText(QtGui.QApplication.translate("MainWindow", "Dump", None, QtGui.QApplication.UnicodeUTF8))

